version: '3.9'
services:
  security-settings:
    build:
      dockerfile: docker/Dockerfile
      args:
        FOLDER: "security"
        PACKAGE_NAME: "security-settings-0.1"
    volumes:
      - ./packages:/output
    profiles:
      - security
      - all
  pki-server:
    build:
      dockerfile: docker/Dockerfile
      args:
        FOLDER: "pki_server"
        PACKAGE_NAME: "pki-server-0.1"
    volumes:
      - ./packages:/output
    profiles:
      - pki
      - all
