groups:
  - name: system
    rules:
      - alert: DiskOutOfSpace
        expr: node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host disk is out of space
          description: "Disk free space is less than 10% \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: DiskInodesOut
        expr: node_filesystem_files_free{mountpoint="/"} / node_filesystem_files{mountpoint="/"} < 0.1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Host disk i-nodes is out
          description: "Disk free i-nodes is less than 10% \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: CpuHighLoad
        expr: node_load5 >= 2
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: High load average
          description: "Load average for 5 mins > 2 cpu core \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: OOM
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Available RAM is low
          description: "Available RAM is less than 10% \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: High load RX
        expr: rate(node_network_receive_bytes_total[1m]) / 1024 / 1024 * 8 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Recieve network speed is too high
          description: "Recieve network speed is higher than 80% limit \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: High load TX
        expr: rate(node_network_transmit_bytes_total[1m]) / 1024 / 1024 * 8 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Transmit network speed is too high
          description: "Transmit network speed is higher than 80% limit \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: IOwait long
        expr: rate(node_cpu_seconds_total{mode="iowait"}[5m]) * 100 > 10
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: IO wait is too long
          description: "IOwait is more, then 10% of CPU time \n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
      - alert: OpenVPN crushed
        expr: node_systemd_unit_state{name="openvpn-server@openvpn.service",state="failed"} == 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: OpenVPN service crashed
          description: "OpenVPN service crashed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
